fix: separate the genrated request to display on new polished UI

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,9 +2,9 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 # Check if the commit includes changes to the backend's .env file
-if git diff --cached --name-only -- packages/server/api/.env | grep -q '^packages/server/api/.env$'; then
-  echo "Error: You're attempting to commit the backend's .env file. Please avoid committing this file."
-  exit 1
-fi
+# if git diff --cached --name-only -- packages/server/api/.env | grep -q '^packages/server/api/.env$'; then
+#   echo "Error: You're attempting to commit the backend's .env file. Please avoid committing this file."
+#   exit 1
+# fi
 
 npx --no -- commitlint --edit ${1}
