fix: show error message when pre push hook fails

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,14 @@
 
 
 # Run lint checks on specific projects
-sudo npx nx affected --target=lint --fix
+sudo npx nx affected --target=lint
+
+EXIT_CODE=$?
+
+# If linting fails, prevent the push
+if [ $EXIT_CODE -ne 0 ]; then
+  echo "❌ Linting failed. Push aborted, fix the linting errors and commit then push again"
+  exit 1
+fi
+
+echo "✅ Linting passed. Proceeding with push."
